### PR TITLE
Update pngjs to 3.0.1

### PR DESCRIPTION
**Pull request by paladox**
https://github.com/lukeapage/pngjs/commits/master

### CODE REVIEW

**Comment by jdforrester** [comment]
What's the breaking change?

**Comment by paladox** [comment]
@jdforrester it may have been https://github.com/lukeapage/pngjs/commit/96c67ea08d3e5106ff49624e8bb47fe5430389f1

But i can't compare the 2.2.0 release as there dosen't seem to be one.

See https://github.com/lukeapage/pngjs/compare/v2.3.0...master

**Comment by paladox** [comment]
I found there change log

"+### 3.0.0 - 03/08/2016
+ - Drop support for node below v4 and iojs. Pin to 2.3.0 to use with old, unsupported or patched node versions."

https://github.com/lukeapage/pngjs#changelog

**Comment by paladox** [comment]
Thanks.

**Pull request merged**
